# ============================================================================
# Seven Sigma — License Server (Cloudflare Workers + D1)
# ----------------------------------------------------------------------------
# 1. Ubah "database_id" di bawah setelah membuat database D1:
#      npx wrangler d1 create quantum-queen-license
# 2. Isi secret password admin (dipakai login dashboard):
#      npx wrangler secret put ADMIN_PASSWORD
# 3. Deploy:
#      npx wrangler deploy
# 4. Inisialisasi tabel database (sekali saja, atau setiap kali schema berubah):
#      npx wrangler d1 execute quantum-queen-license --remote --file=./schema.sql
# ============================================================================

name = "quantum-queen-license"
main = "src/index.js"
compatibility_date = "2025-06-01"

# ------------------------------------------------------------------ D1 (SQL)
[[d1_databases]]
binding = "DB"
database_name = "quantum-queen-license"
database_id = "d6953e25-fc13-40ca-befa-0b88f4ae7b7f"

# --------------------------------------------- Static assets (dashboard SPA)
[assets]
directory = "./public"
binding = "ASSETS"

# ------------------------------------------------------------ Variable vars
[vars]
# Nama produk yang tampil di dashboard & pesan API (boleh diubah)
PRODUCT_NAME = "Seven Sigma"
